[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:livox_ros_driver2]
command=roslaunch livox_ros_driver2 msg_MID360s.launch 
autostart=true
autorestart=false
stderr_logfile=/var/log/livox_ros_driver2.err.log
stdout_logfile=/var/log/livox_ros_driver2.out.log
priority=1
startsecs=5

[program:vanjee_mini_lidar]
command=roslaunch vanjee_mini_lidar vanjee_716mini_lidar_01.launch 
autostart=true
autorestart=false
stderr_logfile=/var/log/vanjee_mini_lidar.err.log
stdout_logfile=/var/log/vanjee_mini_lidar.out.log
priority=2
startsecs=5