[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:orin_errors]
command=rosrun orin_robot orin_errors_publisher
autostart=true
autorestart=true
stdout_logfile=/var/log/orin_errors.out.log
redirect_stderr=true
priority=3
startsecs=5

[program:orin_resource]
command=rosrun orin_robot orin_resource_publisher
autostart=true
autorestart=true
stdout_logfile=/var/log/orin_resource.out.log
redirect_stderr=true
priority=3
startsecs=5

[program:orin_wifi_list]
command=rosrun orin_robot orin_wifi_list_server
autostart=true
autorestart=true
stdout_logfile=/var/log/orin_wifi_list.out.log
redirect_stderr=true
priority=3
startsecs=5

[program:orin_connect_wifi]
command=rosrun orin_robot orin_connect_wifi_server
autostart=true
autorestart=true
stdout_logfile=/var/log/orin_connect_wifi.out.log
redirect_stderr=true
priority=3
startsecs=5

[program:monitor]
command=rosrun orin_robot monitor
autostart=true
autorestart=true
stdout_logfile=/var/log/monitor.out.log
redirect_stderr=true
priority=3
startsecs=5

[program:work_status]
command=rosrun orin_robot work_status_from_start
autostart=true  
autorestart=true
stdout_logfile=/var/log/work_status.out.log
redirect_stderr=true
priority=3
startsecs=5

[program:basic_info]
command=rosrun orin_robot basic_info_node
autostart=true  
autorestart=true
stdout_logfile=/var/log/basic_info.out.log
redirect_stderr=true
priority=3
startsecs=5