oak:
  autostart: false
  fps: 16  # 相机帧率
  imu_fps: 200
  exposure_mode: 3  # 1:手动, 2:自动, 3:自动(带最大曝光时间)
  exposure_time: 3000  # 曝光时间，单位（us），可调节范围：1~33000，仅在手动曝光模式下有效
  sens_iso: 1000  # ISO的值，可调节
  set_manual_wb: false  # 是否设置手动白平衡模式（false为自动白平衡）
  wb_manual: 5000  # 白平衡：3500~7500，仅在手动白平衡模式下有效
  max_exposure_time_us: 3000  # 最大曝光时间，仅在手动曝光模式下有效

# 腕部相机配置
wrist_camera:
  autostart: false
  width: 1280
  height: 720
  compressed_quality: 80  # 压缩图片的质量 (1-100)

# Realsense相机配置
realsense_cameras:
  up:
    autostart: true
    serial_no: "default"  # 进入 sensor 容器使用 rs-enumerate-devices -S 命令查看序列号，如果设置了 serial_no，则 usb_port_id 设置为 default
    usb_port_id: "2-2"  # 半身和人形的usb_port_id为2-3.1，轮臂的为2-2
    launch_file: "rs_camera_upper_d435i.launch"
    color_width: 1280
    color_height: 720
    depth_width: 1280
    depth_height: 720
    initial_reset: false
    enable_pointcloud: false
    respawn: true
    pointcloud_texture_stream: RS2_STREAM_ANY
  down:
    autostart: false
    serial_no: "default"  # 进入 sensor 容器使用 rs-enumerate-devices -S 命令查看序列号，如果设置了 serial_no，则 usb_port_id 设置为 default
    usb_port_id: "default"  # 腹部相机的usb_port_id为2-3.4
    launch_file: "rs_camera_down_d435i.launch"
    color_width: 1280
    color_height: 720
    depth_width: 1280
    depth_height: 720
  head:
    autostart: false
    serial_no: "default"  # 进入 sensor 容器使用 rs-enumerate-devices -S 命令查看序列号，如果设置了 serial_no，则 usb_port_id 设置为 default
    usb_port_id: "2-1"  # 轮臂的头部相机默认在2-1口，半身和人形没有头部相机
    launch_file: "rs_camera_head_d435i.launch"
    color_width: 1280
    color_height: 720
    depth_width: 1280
    depth_height: 720
    initial_reset: false
    respawn: true

    