[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:nviz]
command=bash /opt/ros/noetic/share/nviz/scripts/run.sh
autostart=true
autorestart=false
stderr_logfile=/var/log/nviz.err.log
stdout_logfile=/var/log/nviz.out.log
priority=1
startsecs=5