[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:nav_planner]
command=bash -c "cd /opt/ros/noetic/share/navigation/scripts && ./launch.sh"
autostart=true
autorestart=false
stderr_logfile=/var/log/nav_planner.err.log
stdout_logfile=/var/log/nav_planner.out.log
priority=1
startsecs=5