database_dir: "/datasets"
# database_name: "250826_shwl3dgs2m"
database_name: "251022_ysq4f"
asmk_params: "./db_asmk.yaml"
draw_results: false

global_retrieval:
  retrieval_k: 10 # ! use query_ivf search topk
  gpu_id: 0

local_matcher:
  inlier_num: 50 # yyl: 60 qsdjt: 80 
  reproj_thresh: 8
  pnp_max_iter: 2
  use_homoransac: true
  use_pnpransac: true
  viewer_record_flag: true
  visual_flag: false
  colmap_camera_id: [3, 1, 2] # index to camera_id, [left, stereo_left, right], for realtime
  # colmap_camera_id: [0, 2, 3] # index to camera_id, [left, stereo_left, right], for test
  use_gpu: true
