[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:dproxy]
command=/navi_ws/install/lib/dproxy/dproxy
autostart=true
autorestart=true
stdout_logfile=/var/log/dproxy.out.log
redirect_stderr=true
priority=2
startsecs=5

[program:python_script]
command=python3 /navi_ws/src/dproxy/scripts/dproxy_servers.py
autostart=true
autorestart=true
stdout_logfile=/var/log/dproxy_servers.out.log
redirect_stderr=true
priority=5
startsecs=5 

[program:rosbridge_server]
command=roslaunch rosbridge_server rosbridge_websocket.launch
autostart=true
autorestart=true
stdout_logfile=/var/log/rosbridge_server.out.log
redirect_stderr=true
priority=6
startsecs=5

[program:foxglove_bridge_server]
command=roslaunch foxglove_bridge foxglove_bridge.launch
autostart=true
autorestart=true
stdout_logfile=/var/log/foxglove_bridge.out.log
redirect_stderr=true
priority=6
startsecs=5

[program:state_monitor]
command=rosrun dproxy state_monitor.py
autostart=true
autorestart=true
stdout_logfile=/var/log/state_monitor.out.log
redirect_stderr=true
priority=6
startsecs=5 

