version: 1
description: no localization rules

rules:
  rule_1:
    op: and
    conditions:
      - type: compare
        field: result.success
        op: equals
        cast: boolean
        value: true
      - type: compare
        field: result.data.output.stdout
        extract:
          type: regex
          pattern: "point_num:\\s*(\\d+)"
          group: 1
        op: greater_than
        cast: number
        value: 0

  rule_2:
    op: and
    conditions:
      - type: compare
        field: result.success
        op: equals
        cast: boolean
        value: true
      - type: compare
        field: result.data.output.stdout
        op: not_empty
      - type: compare
        field: result.data.output.stdout
        op: not_contains
        value: ERROR
      - type: compare
        field: result.data.output.stdout
        op: not_contains
        value: failed
      - type: compare
        field: result.data.output.stdout
        op: not_contains
        value: exception

  rule_3:
    op: and
    conditions:
      - type: compare
        field: result.success
        op: equals
        cast: boolean
        value: true
      - type: compare
        field: result.data.output.stdout
        op: regex_match
        value: "(?m)^\\s*(?:x|y|z):\\s*(?!0(?:\\.0+)?(?:\\s|$))[-+]?(?:\\d+(?:\\.\\d+)?|\\.\\d+)"
