[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:catkin_make]
command=bash -c "cd /navi_ws && catkin_make -DCMAKE_INSTALL_PREFIX='/opt/ros/noetic' -j$(nproc) && cd build && make install"
autostart=true
autorestart=false
stderr_logfile=/var/log/catkin_make.err.log
stdout_logfile=/var/log/catkin_make.out.log
priority=1
startsecs=5

[program:rosbridge_server]
command=roslaunch rosbridge_server rosbridge_websocket.launch
autostart=true
autorestart=false
stderr_logfile=/var/log/rosbridge_server.err.log
stdout_logfile=/var/log/rosbridge_server.out.log
priority=5
startsecs=5