action: /zj_humanoid/navigation/navigation
topics:
  map:
    name: /zj_humanoid/navigation/map
    is_record: true
    is_playback: true
    is_feedback: true
  odometry:
    name: /zj_humanoid/navigation/odom_info
    is_record: true
    is_playback: true
    is_feedback: true
  obstacle:
    name: /zj_humanoid/navigation/local_map
    is_record: true
    is_playback: true
    is_feedback: true
  module_status:
    name: /zj_humanoid/navigation/navigation_code
    is_record: true
    is_playback: true
    is_feedback: false
  control_command:
    name: /zj_humanoid/cmd_vel/calib
    is_record: true
    is_playback: true
    is_feedback: false
  navigation_debug:
    name: /zj_humanoid/navigation/navigation_debug
    is_record: true
    is_playback: true
    is_feedback: false
  path:
    name: /zj_humanoid/navigation/path
    is_record: true
    is_playback: true
    is_feedback: false
  trajectory:
    name: /zj_humanoid/navigation/trajectory
    is_record: true
    is_playback: true
    is_feedback: false
  mpc_trajectory:
    name: /zj_humanoid/navigation/mpc_trajectory
    is_record: true
    is_playback: true
    is_feedback: false
action_topics:
  goal:
    is_record: true
    is_playback: true
    is_feedback: true
  result:
    is_record: true
    is_playback: true
    is_feedback: false
  cancel:
    is_record: true
    is_playback: true
    is_feedback: true
  status:
    is_record: true
    is_playback: true
    is_feedback: false
  feedback:
    is_record: true
    is_playback: true
    is_feedback: false
