[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:map_server]
command=rosrun nav_map_server nav_map_server_node
autostart=true
autorestart=false
stderr_logfile=/var/log/map_server.err.log
stdout_logfile=/var/log/map_server.out.log
priority=1
startsecs=5