action: /zj_humanoid/navigation/navigation
input_topics:
  map: /zj_humanoid/navigation/map
  odometry: /zj_humanoid/navigation/odom_info
  obstacle: /zj_humanoid/navigation/local_map
output_topics:
  module_status: /zj_humanoid/navigation/navigation_code
  control_command: /zj_humanoid/cmd_vel/calib
  path: /zj_humanoid/navigation/path
  trajectory: /zj_humanoid/navigation/trajectory
  mpc_trajectory: /zj_humanoid/navigation/mpc_trajectory
  navigation_debug: /zj_humanoid/navigation/navigation_debug