[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:static_tf]
command=roslaunch location static_tf.launch
autostart=true
autorestart=false
stderr_logfile=/var/log/static_tf.err.log
stdout_logfile=/var/log/static_tf.out.log
priority=1
startsecs=5 

[program:lio_srv]
command=roslaunch location lio.launch
autostart=true
autorestart=false
stderr_logfile=/var/log/lio_srv.err.log
stdout_logfile=/var/log/lio_srv.out.log
priority=2
startsecs=5 

[program:mapping_srv]
command=rosrun voxel_slam mapping_srv
autostart=true
autorestart=false
stderr_logfile=/var/log/mapping_srv.err.log
stdout_logfile=/var/log/mapping_srv.out.log
priority=2
startsecs=5 

[program:post_processing_srv]
command=rosrun voxel_slam post_processing_srv
autostart=true
autorestart=false
stderr_logfile=/var/log/post_processing_srv.err.log
stdout_logfile=/var/log/post_processing_srv.out.log
priority=2
startsecs=5 

[program:octree]
command=roslaunch perception perception.launch
autostart=true
autorestart=false
stderr_logfile=/var/log/octree.err.log
stdout_logfile=/var/log/octree.out.log
priority=3
startsecs=5 