[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:static_tf]
command=roslaunch ov_msckf static_tf.launch
autostart=true
autorestart=false
stderr_logfile=/var/log/static_tf.err.log
stdout_logfile=/var/log/static_tf.out.log
priority=1
startsecs=5 

[program:vio]
command=roslaunch ov_msckf subscribe.launch
autostart=true
autorestart=false
stderr_logfile=/var/log/vio.err.log
stdout_logfile=/var/log/vio.out.log
priority=2
startsecs=5 

[program:octree]
command=roslaunch perception perception.launch
autostart=true
autorestart=false
stderr_logfile=/var/log/octree.err.log
stdout_logfile=/var/log/octree.out.log
priority=3
startsecs=5 