[supervisord]
nodaemon=true  ; supervisor运行时不以守护进程模式运行，适合容器
user=root

[program:audio_system]
command=bash -c "source /opt/ros/noetic/setup.bash && roslaunch naviai_audio_launch audio_system.launch enable_mic:=%(ENV_ENABLE_MIC)s enable_speaker:=%(ENV_ENABLE_SPEAKER)s --wait"
autostart=true
autorestart=true
stderr_logfile=/var/log/audio_system.err.log
stdout_logfile=/var/log/audio_system.out.log
priority=1
startsecs=10
environment=PYTHONUNBUFFERED="1",ROSCONSOLE_STDOUT_LINE_BUFFERED="1"
